# Generated by Django 3.0.1 on 2021-02-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_result_quantitative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spatial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('la', models.ImageField(max_length=500, upload_to='')),
                ('lb', models.ImageField(max_length=500, upload_to='')),
                ('lc', models.ImageField(max_length=500, upload_to='')),
                ('ld', models.ImageField(max_length=500, upload_to='')),
                ('ans', models.ImageField(max_length=500, upload_to='')),
            ],
        ),
    ]
