# Generated by Django 3.0.1 on 2021-02-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_spatial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatial',
            name='ans',
            field=models.CharField(max_length=500),
        ),
    ]
