# Generated by Django 3.0.1 on 2021-03-26 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0011_result_spatial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('head_shot', models.ImageField(blank=True, upload_to='profil_images')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
